# Generated by Django 4.2.7 on 2023-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealweek',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
